Share document with link
viniciusilveira/elixir-google-drive-api pull request #15
Opened 2017-12-06 12:50 UTC by francolucas

This new function adds the ability to change the document's permission to share with everyone with the link.

2017-12-06 12:52 UTC, viniciusilveira commented
:heart:

2017-12-06 12:53 UTC, viniciusilveira approved these changes

2017-12-06 13:07 UTC, caironoleto requested changes

2017-12-06 13:07 UTC, caironoleto commented on lib/elixir_google_drive_api/drive.ex
> +   "https://www.googleapis.com/drive/v2/files/#{file_id}/permissions"
This domain is duplicated. I think you can move it to one function.

2017-12-06 13:07 UTC, caironoleto commented on lib/elixir_google_drive_api/drive.ex
> +      {:ok, %HTTPoison.Response{body: response_body}} ->
This code is duplicated (see line 59-62), you can do something like this:

```elixir
def insert_permission_file(file_id, headers, body \\ "") do
  request(:post, insert_permission_url(file_id), body, headers)
end

defp request(method, url, body, headers) do
  HTTPoison.request(method, url, body, headers do
    {:ok, %HTTPoison.Response{body: response_body}} ->
      response_body |> Poison.decode!
    {:error, %HTTPoison.Error{reason: reason}} -> reason
  end
end
```

2017-12-07 11:47 UTC, caironoleto approved these changes

2017-12-07 11:53 UTC, renanlopescoder approved these changes

2017-12-07 15:18 UTC, viniciusilveira approved these changes

2017-12-07 15:18 UTC, merged